server:
  port: 8083
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: rest-simple-example
  devtools:
    remote:
      restart:
        enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    open-in-view: false
    hibernate:
      ddl-auto: update 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_example?useSSL=false&serverTimezone=UTC&maxReconnects=10&autoReconnect=true&nullNamePatternMatchesAll=true
    username: root
    password: nikola
    #initialization-mode: always  
